"""initial

Revision ID: a82ebcf6521b
Revises: 
Create Date: 2026-05-27 23:48:47.112168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82ebcf6521b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('PACIENTE', 'RESPONSAVEL', 'CUIDADOR', name='tipousuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('obs_medicas', sa.Text(), nullable=True),
    sa.Column('nivel_autonomia', sa.Enum('TOTAL', 'PARCIAL', 'DEPENDENTE', name='nivelautonomia'), nullable=True),
    sa.Column('grau_parentesco', sa.String(length=100), nullable=True),
    sa.Column('recebe_notificacoes', sa.Boolean(), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medicamentos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.BigInteger(), nullable=False),
    sa.Column('categoria_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=100), nullable=False),
    sa.Column('instrucoes', sa.Text(), nullable=False),
    sa.Column('uso_continuo', sa.Boolean(), nullable=False),
    sa.Column('necessita_retorno', sa.Boolean(), nullable=False),
    sa.Column('intervalo_retorno_dias', sa.Integer(), nullable=True),
    sa.Column('data_inicio_tratamento', sa.Date(), nullable=False),
    sa.Column('data_proximo_retorno', sa.Date(), nullable=True),
    sa.Column('retorno_realizado', sa.Boolean(), nullable=True),
    sa.Column('data_retorno_realizado', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.BigInteger(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_por', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vinculos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('responsavel_id', sa.BigInteger(), nullable=False),
    sa.Column('paciente_id', sa.BigInteger(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vinculo_ativo_unique', 'vinculos', ['responsavel_id', 'paciente_id'], unique=True, postgresql_where=sa.text('ativo = true'))
    op.create_table('agendas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('medicamento_id', sa.BigInteger(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('frequencia', sa.Enum('DIARIA', 'SEMANAL', 'PERSONALIZADA', name='frequenciatomada'), nullable=False),
    sa.Column('dias_semana', sa.String(length=20), nullable=True),
    sa.Column('tolerancia_minutos', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_tomada',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agenda_id', sa.BigInteger(), nullable=False),
    sa.Column('paciente_id', sa.BigInteger(), nullable=False),
    sa.Column('data_hora_prevista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_confirmacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'ATRASADO', 'IGNORADO', name='statustomada'), nullable=False),
    sa.Column('usuario_confirmacao_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_confirmacao_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id', 'data_hora_prevista', name='uq_agenda_data_hora_prevista')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('registro_tomada_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo', sa.Enum('LEMBRETE', 'FALHA_TOMADA', 'RETORNO_MEDICO', name='tiponotificacao'), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registro_tomada_id'], ['registros_tomada.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('registros_tomada')
    op.drop_table('agendas')
    op.drop_index('ix_vinculo_ativo_unique', table_name='vinculos', postgresql_where=sa.text('ativo = true'))
    op.drop_table('vinculos')
    op.drop_table('refresh_tokens')
    op.drop_table('medicamentos')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
